<?php

namespace AppBundle\Repository;

/**
 * fredRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class fredRepository extends \Doctrine\ORM\EntityRepository
{
}
